### ISSUE TITLE
Add LITE vs PRO

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/strong-testimonials#167]
**Is your feature request related to a problem? Please describe.**
Problem doesn't exist, yet :D 

**Describe the solution you'd like**
Lite vs pro comparison like we have for Modula

**Comment by giucu91** [comment]
this needs to have a separate page.

**Comment by razvanaldea89** [comment]
Replace current Upgrade page with the Free vs PRO like Modula's, the simple one, which will remove current bugs: 

![image](https://user-images.githubusercontent.com/44024114/158373014-fd73bb76-6e63-4d68-970e-b5fe8563b4e3.png)

**Comment by razvanaldea89** [comment]
New LITE vs PRO page: 

![image](https://user-images.githubusercontent.com/44024114/158810865-c30f25ec-b8eb-4907-967a-550cc1cfa8de.png)
