### ISSUE TITLE
Slider not working properly on firefox

### ISSUE THREAD

**Issue by ViSi19** [WPChill/strong-testimonials#191]
**Describe the bug**
https://wordpress.org/support/topic/firefox-browser-only-displaying-navigation-controls/ 
On firefox, even when the respective page in the ticket is opened, more precisely http://duncansdrivingschool.co.uk/ it does not load but after the first refresh it works correctly.

**To Reproduce**
1. Go to firefox
2. paste this link http://duncansdrivingschool.co.uk/
3. Scroll down to Testimonial slider
4. See error -> not working

**Expected behavior**

**Screenshots**
https://gyazo.com/d757dec9de4ef08d1249cd06766e8a79

* Which addons do you have installed: 
- [ ] Country Selector
- [ ] Assignment
- [ ] SEO-friendly Markup
- [ ] Custom Properties
- [ ] Advanced Views
- [ ] Spam Control
- [ ] Pro Templates
- [ ] External Platform Importer
- [ ] Custom Form Fields
- [ ] Multiple Forms

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ x] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other

**Comment by Florin415** [comment]
tested by me and @cristinnaiulia , works on our end : https://prnt.sc/v2sdqf , https://prnt.sc/v2sdw2
