### ISSUE TITLE
The styling is broken on the Extensions Tab

### ISSUE THREAD

**Issue by Florin415** [WPChill/strong-testimonials#205]
**Describe the bug**
If you go to the Extensions tab you will see that the elements are no longer styled in the page.

**To Reproduce**
1. Install Strong Testimonials using the plugins tab in WP
2. Activate the Plugin
3. Go to the Extensions page

**Expected behavior**
The elements in the page to have the previews style applied to them 

**Screenshots**
https://prnt.sc/wgpbey

* Which addons do you have installed: 
- [ ] Country Selector
- [ ] Assignment
- [ ] SEO-friendly Markup
- [ ] Custom Properties
- [ ] Advanced Views
- [ ] Spam Control
- [ ] Pro Templates
- [ ] External Platform Importer
- [ ] Custom Form Fields
- [ ] Multiple Forms

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 5.6
* Strong Testimonials version: 2.50.4 
* Country Selector version: 
* Assignment version: 
* SEO-friendly Markup version: 
* Custom Properties version: 
* Advanced Views version: 
* Spam Control version: 
* Pro Templates version: 
* External Platform Importer version: 
* Custom Form Fields version: 
* Multiple Forms version:

**Comment by cristinnaiulia** [comment]
For testing you need the loadbutton branch.
