### ISSUE TITLE
preserve HTML in testimonials

### ISSUE THREAD

**Issue by mplusb** [WPChill/strong-testimonials#206]
**Is your feature request related to a problem? Please describe.**
We would like to preserve HTML markup in a testimonial post. Right now not all HTML is preserved. For instance we have some products that require a superscript in their name.

Here is an example of it not working as we expected.
![image004](https://user-images.githubusercontent.com/26008574/103648185-1eaede80-4f65-11eb-911e-5ffe5dcec30b.jpg)
![image005](https://user-images.githubusercontent.com/26008574/103648190-1fe00b80-4f65-11eb-9ecf-0fe339d7c987.jpg)
![image013](https://user-images.githubusercontent.com/26008574/103648193-2078a200-4f65-11eb-93ab-dc04dacb3e53.jpg)

**Describe the solution you'd like**
It would be great if we could have free form HTML in the post content section.

**Comment by giucu91** [comment]
@cristinnaiulia why do we use strip_tags instead of wp_kses_post( https://developer.wordpress.org/reference/functions/wp_kses_post/ ) ?

**Comment by cristinnaiulia** [comment]
We use -- strip_tags -- in order to be selective on the tags we need to strip. If we use -- wp_kses_post -- the read more button from excerpt doesn't work.
