### ISSUE TITLE
Testimonials not Being Accepted through Mobile

### ISSUE THREAD

**Issue by mplusb** [WPChill/strong-testimonials#213]
**Describe the bug**
Am Using version 2.5.4 of Strong Testimonials Plugin.
The testimonials when entered through a Mobile do not reflect or get accepted. Doesn’t throw an error or even a success message & the writer gets an expression that its submitted.

However, there’s is no problem when submitting the testimonial on a PC/Laptop. The success message is shown & it immediately reflects in the Admin Dashboard.

**Google Recaptcha is not a problem at all. However, my form asks for a Image to be uploaded(*required) by the person writing a testimonial & that’s where the real problem is. Sometimes it accepts the image & sometimes it doesn’t(Only on Mobile)

Now, i have removed/deleted the Image requirement from my form & each time its accepting a testimonial.**

**To Reproduce**
1. create a form
2. add a required photo field 
3. try to submit a testimonial. Try with several image types to see which is causing an error

**Expected behavior**
This is most likely an issue from the images uploaded (could be too large, not accepted format), but such errors are not displayed on the front-end. Because of that neither us or the user submitting a testimonials does not know what happens exactly so it can be fixed.
**add a way of displaying image related errors when a testimonial is submitted.** 

**Screenshots**
https://wordpress.org/support/topic/testimonials-not-being-accepted-through-mobile/

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [x] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 5.6
* Strong Testimonials version: 2.50.4

**Comment by TeoAlex** [comment]
Could not reproduce the issue.

**Comment by mplusb** [comment]
no longer happens with the latest version of the plugin 3.1.9 @razvanaldea89

**Comment by mplusb** [comment]
seems to be working ok with latest version 3.1.9 - cannot replicate
