### ISSUE TITLE
Refactoring View sections and options

### ISSUE THREAD

**Issue by cristinnaiulia** [WPChill/strong-testimonials#222]

**Comment by razvanaldea89** [comment]
Has another 2 commits : https://github.com/WPChill/strong-testimonials/commit/5c35abc31c62250e9d45511f80508465a977b749 and https://github.com/WPChill/strong-testimonials/commit/8013ad9ae8ad862825b57357b8edcf41b687f4a2

**Comment by razvanaldea89** [comment]
Seems to be fine, but have to keep in mind the classes that extend this one, for example in Review Markup there is a method called `description` that was supposed to be here ( not existing in child class ) that isn't and will trigger error.
