### ISSUE TITLE
compatibility issues with https://wordpress.org/plugins/clearfy/

### ISSUE THREAD

**Issue by mplusb** [WPChill/strong-testimonials#223]
**Describe the bug**
compatibility issues with https://wordpress.org/plugins/clearfy/

Hi i have recently installed the app however the tag data-src is not rendering the image, only if i remove the data- does it show, any suggestions? I have tried in several browsers.
<img width="150" height="150" class="attachment-thumbnail size-thumbnail wp-post-image" alt="I really enjoyed the course" loading="lazy" sizes="(max-width: 150px) 100vw, 150px" data-src="https://......../wp-content/uploads/2021/03/woman-head-150x150.png" title="I really enjoyed the course">

it seems it is Webcraftic Robin image optimizer, part of Webcraftic Clearfy – WordPress optimization plugin

#### Used versions
* WordPress version: 5.6.2
* Strong Testimonials version: 2.51.2

https://wordpress.org/support/topic/data-src-not-showing-images/

**Comment by TeoAlex** [comment]
Could not reproduce the issue.
