### ISSUE TITLE
Hook

### ISSUE THREAD

**Issue by giucu91** [WPChill/strong-testimonials#227]
**Describe the bug**
https://github.com/WPChill/strong-testimonials/blob/bb6fad6f080f364f8116cf6b2a9de05036d87f0c/admin/class-strong-testimonials-helper.php#L831

Here we need a hook, a do_action

**Comment by cristinnaiulia** [comment]
It was added in this commit -> https://github.com/WPChill/strong-testimonials/commit/ff126350058132a18351706859d792fff80a64df
