### ISSUE TITLE
Escape and sanitization

### ISSUE THREAD

**Issue by giucu91** [WPChill/strong-testimonials#229]
https://github.com/WPChill/strong-testimonials/blob/bb6fad6f080f364f8116cf6b2a9de05036d87f0c/admin/class-strong-testimonials-helper.php#L752

**Comment by giucu91** [comment]
https://github.com/WPChill/strong-testimonials/blob/dev/admin/class-strong-testimonials-helper.php#L601

**Comment by cristinnaiulia** [comment]
Nu se poate pune escape
https://github.com/WPChill/strong-testimonials/blob/dev/admin/class-strong-testimonials-helper.php#L534
EXCERPT
https://github.com/WPChill/strong-testimonials/blob/be2c018aa2088e748a4cad485596af91346cd523/admin/class-strong-testimonials-helper.php#L1102
Labels
After/Before
