### ISSUE TITLE
missing excerpt when editing a testimonial with Divi's builder

### ISSUE THREAD

**Issue by mplusb** [WPChill/strong-testimonials#231]
**Describe the bug**
the same as here: https://github.com/WPChill/strong-testimonials/issues/220
But now it's only missing if you edit a testimonial with Divi builder. If you switch to classic editor, the excerpt will then display in the view.

**To Reproduce**
Go to Testimonials > edit a testimonial > add an excerpt > and then edit it with divi builder > add whatever in the testimonial content
> when you go to the page where the View is > the excerpt will no display
https://wordpress.org/support/topic/missing-excerpts-2/

**Screenshots**
![excerpts1](https://user-images.githubusercontent.com/26008574/111169483-accdc380-85ab-11eb-84b9-9ad20c636eb5.jpg)
![excerpts2](https://user-images.githubusercontent.com/26008574/111169484-ad665a00-85ab-11eb-80cc-167f01a6ffc4.png)

![Sn-mka-obrazovky-2021-03-10-101728](https://user-images.githubusercontent.com/26008574/111169623-ce2eaf80-85ab-11eb-8199-9e91c710779b.jpg)
![Sn-mka-obrazovky-2021-03-10-101906](https://user-images.githubusercontent.com/26008574/111169624-cec74600-85ab-11eb-8238-c6a2aad1ada5.jpg)

#### Used versions
* WordPress version: 5.7
* Strong Testimonials version: 2.51.2

**Comment by razvanaldea89** [comment]
This fix seems to be already deployed. Going to close this ticket
