### ISSUE TITLE
issue with the view being reset to None in the editor. 

### ISSUE THREAD

**Issue by mplusb** [WPChill/strong-testimonials#232]
**Describe the bug**
 issue with the view being reset to None in the editor. This happens while working on other elements, so it's easy to overlook. And of course with the view set to none, there are empty spaces on the home page where there should be testimonials.

You select a view > save the page > and then if you edit the page again is says:  None > and if the page is saved like this then you have no views displayed.

**To Reproduce**
Please see: 
[Screen Recording 2021-03-22 at 12.27.46.zip](https://github.com/WPChill/strong-testimonials/files/6181383/Screen.Recording.2021-03-22.at.12.27.46.zip)

#### Used versions
* WordPress version: 5.7
* Strong Testimonials version: 2.51.2

**Comment by andyluak** [comment]
Please test with 2.51.3

**Comment by mplusb** [comment]
works with the latest version
