### ISSUE TITLE
jquery strong slider public methods

### ISSUE THREAD

**Issue by giucu91** [WPChill/strong-testimonials#233]
**Describe the bug**
We need to change `$(el).data('strongSlider', this);` with `$(el).data('strongSlider', el)` in order to allow users to acces the public methods of bxSlider ( https://bxslider.com/options/ )

https://github.com/WPChill/strong-testimonials/blob/master/public/js/lib/strongslider/jquery-strongslider.js#L1984

At us `this` isn't the same with `el` like in bxslider : 
bxslider: https://github.com/stevenwanderski/bxslider-4/blob/master/src/js/jquery.bxslider.js#L112
strongslider : https://github.com/WPChill/strong-testimonials/blob/master/public/js/lib/strongslider/jquery-strongslider.js#L120

* Which addons do you have installed: 
- [ ] Country Selector
- [ ] Assignment
- [ ] SEO-friendly Markup
- [ ] Custom Properties
- [ ] Advanced Views
- [ ] Spam Control
- [ ] Pro Templates
- [ ] External Platform Importer
- [ ] Custom Form Fields
- [ ] Multiple Forms

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Strong Testimonials version: 
* Country Selector version: 
* Assignment version: 
* SEO-friendly Markup version: 
* Custom Properties version: 
* Advanced Views version: 
* Spam Control version: 
* Pro Templates version: 
* External Platform Importer version: 
* Custom Form Fields version: 
* Multiple Forms version:

**Comment by hahn208** [comment]
Note the second reference that would need updated also:
https://github.com/WPChill/strong-testimonials/blob/master/public/js/lib/strongslider/jquery-strongslider.js#L1977

Sample usage:
`$('.wpmslider-content').data('strongSlider').goToPrevSlide();`
