### ISSUE TITLE
outline the stars for accessibility reasons

### ISSUE THREAD

**Issue by mplusb** [WPChill/strong-testimonials#237]
**Is your feature request related to a problem? Please describe.**
Client feedback: I was taking an accessibility course and they explained that yellow stars on light backgrounds are hard for people with vision issues to see - they recommended outlining the stars to improve accessibility scores.

**Describe the solution you'd like**
the option to outline the stars with a different color

**Comment by razvanaldea89** [comment]
The half star mask overflows the container ( newly added outline ) for some reason.
![image](https://user-images.githubusercontent.com/44024114/136788543-ffea8ce3-5654-4f1d-9abd-235636055c7f.png)

**Comment by razvanaldea89** [comment]
@TeoAlex please enter the SVG everywhere the stars are present - for example in the Form. Also, please put stroke-width on the SVG for about 6px, think it looks better that way.

**Comment by TeoAlex** [comment]
https://github.com/WPChill/strong-testimonials/commit/dd2346ffd31c45eede3981a3f090dab8fff20335

**Comment by razvanaldea89** [comment]
Seems OK now
