### ISSUE TITLE
the field for “Company Name” on by default when creating a new view

### ISSUE THREAD

**Issue by mplusb** [WPChill/strong-testimonials#240]
**Describe the bug**
I’ve noticed that the field for “Company Name” always appears in the list of default fields when creating a new view, even if it has been removed via the form editor. I know it’s just a few quick steps to remove it from my view, but it’s frustrating always seeing “Company Name < ERROR – not found >” in red.

**To Reproduce**
1. Go to Form > remove company name
2. Go to Views > add a new view > see the error

**Expected behavior**
if it's remove from the form it shouldn't add it automatically in a view

#### Used versions
* WordPress version: 5.7
* Strong Testimonials version: 2.51.3

**Comment by razvanaldea89** [comment]
Removed fields will be removed from all views
