### ISSUE TITLE
Couldn't save testimonial from admin panel.

### ISSUE THREAD

**Issue by mah3uz** [WPChill/strong-testimonials#250]
**Describe the bug**
When trying to save, Doesn't save testimonial from admin panel.
it says `Publishing failed. No route was found matching the URL and request method.`

#### Used versions
* WordPress version: 5.6
* Strong Testimonials version: 2.51.4

**Comment by mplusb** [comment]
Hi @mah3uz,


We tried several times but are unable to replicate this issue.
Could you please send us a bit more details about this? Are you willing to send us a video with the issue - that would really help.
Also could you please send us a list with your plugins and the ST settings? And what PHP version do you have?

**Comment by mah3uz** [comment]
@mplusb Thank you for the reply. We are in holiday, would send more details after next week.

**Comment by razvanaldea89** [comment]
Hey @mah3uz , you did not come with any details regarding the saving process. Is it fixed now, did you encounter any problems with other plugins/themes?

**Comment by razvanaldea89** [comment]
Going to close this for lack of info. If anyone else experiences this or the OP comes back issue will be reopened
