### ISSUE TITLE
read more not show when using Japanese

### ISSUE THREAD

**Issue by mplusb** [WPChill/strong-testimonials#251]
**Describe the bug**
https://wordpress.org/support/topic/read-more-not-show-and-500-error/

**To Reproduce**
1. add a testimonial in Japanese
2. go to Views > automatic excerpt > enter a number > see the error on the page.
3. it will show the whole testimonial

#### Used versions
* WordPress version: 5.7.1
* Strong Testimonials version: 2.51.4

**Comment by cristinnaiulia** [comment]
The text is being split by number of words using spaces as delimiter. Since the Japanese language doesn't use spaces, the text is seen as a single word and cannot be split.  

![Screenshot_1](https://user-images.githubusercontent.com/63049546/117994914-8f1da000-b349-11eb-97df-9dc8c5da152b.png)
