### ISSUE TITLE
error on the WAVE accessibility report

### ISSUE THREAD

**Issue by mplusb** [WPChill/strong-testimonials#253]
**Is your feature request related to a problem? Please describe.**
I'm getting an error on the WAVE accessibility report because the slider arrow links don't have any text. You can see what I mean here: https://wave.webaim.org/report

**Describe the solution you'd like**
a way to filter the output and include some screen reader text

**Comment by mplusb** [comment]
<img width="1431" alt="Screenshot 2021-04-28 at 10 34 08" src="https://user-images.githubusercontent.com/26008574/116364830-4a541e00-a80d-11eb-9a8e-2d11fb5a4be3.png">

**Comment by razvanaldea89** [comment]
@cristinnaiulia please also make the new texts translatable
