### ISSUE TITLE
 Fatal error caused wp_lazy_loading_enabled filter

### ISSUE THREAD

**Issue by mplusb** [WPChill/strong-testimonials#254]
**Describe the bug**
fatal error when you install Swift Performance: https://wordpress.org/plugins/swift-performance-lite/
https://wordpress.org/support/topic/fatal-error-caused-wp_lazy_loading_enabled-filter/

**To Reproduce**
1. install that plugin
2. Click on the page where your ST view is
3. See error

#### Used versions
* WordPress version: 5.7.1
* Strong Testimonials version: 2.51.4

**Comment by razvanaldea89** [comment]
Seems to be working now, although Swift Performance plugin issued a fix as well
