### ISSUE TITLE
multisite problem

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/strong-testimonials#263]
**Describe the bug**

I did an installation on a multisite but sadly got an error on all except the main site:

/home/suissetp/public_html/suisse-tp_ch/suisse-tp_ch/web/wp/wp-content/plugins/strong-testimonials/includes/functions-views.php:34 Stack trace: #0 /home/suissetp/public_html/suisse-tp_ch/suisse-tp_ch/web/wp/wp-content/plugins/strong-testimonials/includes/class-strong-gutemberg.php(36): wpmtst_get_views() #1 /home/suissetp/public_html/suisse-tp_ch/suisse-tp_ch/web/wp/wp-includes/class-wp-hook.php(292): Strong_Gutemberg->generate_js_vars('') #2 /home/suissetp/public_html/suisse-tp_ch/suisse-tp_ch/web/wp/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array) #3 /home/suissetp/public_html/suisse-tp_ch/suisse-tp_ch/web/wp/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #4 /home/suissetp/public_html/suisse-tp_ch/suisse-tp_ch/web/wp/wp-settings.php(560): do_action('init') #5 /home/suissetp/public_html/suisse-tp_ch/suisse-tp_ch/web/wp/wp-config.php(99): require_once('/home/suissetp/...') #6 /home/suissetp/public_html/suisse-tp_ in /home/suissetp/public_html/suisse-tp_ch/suisse-tp_ch/web/wp/wp-content/plugins/strong-testimonials/includes/functions-views.php on line 34

I removed “strong testimonials, installed “propper network installations” and re-added “strong testimonials” but the error remains.

https://wordpress.org/support/topic/multisite-problem-43/

**Comment by TeoAlex** [comment]
Tested with multisite on wp 4.8.1 and php 8. No problems were found.
