### ISSUE TITLE
Please unload the plugin js and css on pages where shortcodes aren’t present

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/strong-testimonials#285]
More details: https://wordpress.org/support/topic/beautifully-shaped-and-eye-catching/

**Comment by TeoAlex** [comment]
The issue could not be reproduced. A link to a page in the site were the scripts are present without the shordcode being used might help us better identify the issue.

**Comment by razvanaldea89** [comment]
Will close this as we can't replicate and OP doesn't anwser
