### ISSUE TITLE
column view glitch

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/strong-testimonials#288]
**Describe the bug**
When clicking on a new tab, the testimonial slideshow shows as one column and then changes over to the 3 columns (which it is suppose to be). I just want it to initially show as the 3 columns instead of having to wait for it to switch over
https://wordpress.org/support/topic/column-view-glitch/
https://secure.helpscout.net/conversation/1692570381/42260?folderId=4656052

**To Reproduce**
1. Go to Testimonials > create a slideshow view > go to Pages > Edit with Elementor > search for 'Tabs' > drag the widget > add the testimonials view shortcode in Tab 1 and Tab 2 > Publish.
2. Go to the page you created > click on Tab 1 > Click on Tab 2 
3.  See error

**Expected behavior**
The 3 columns should appear automatically when you click on another tab 

* Which browser is affected (or browsers): 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [x] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Strong Testimonials version: 2.51.6
* Country Selector version: 
* Assignment version: 
* SEO-friendly Markup version: 
* Custom Properties version: 
* Advanced Views version: 
* Spam Control version: 
* Pro Templates version: 
* External Platform Importer version: 
* Custom Form Fields version: 
* Multiple Forms version:

**Comment by razvanaldea89** [comment]
@TeoAlex I think this one was solved. Could you please check?
