### ISSUE TITLE
Slideshow view not displaying correct number of slides

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/strong-testimonials#289]
**Describe the bug**
I have a slideshow view set to show 4 slides, however only one shows at a time. I troubleshoot and it seems there is a conflict with another one of our plugins called MemberMouse, however this is a must-have plugin for us and we cannot disable it. Anyway to fix this issue and get the slideshow to display correctly with both plugins?
https://wordpress.org/support/topic/slideshow-view-not-displaying-correct-number-of-slides/#post-15135913

**Comment by giucu91** [comment]
@beatricelucaci do we have the MemberMouse plugin ?

**Comment by beatricelucaci** [comment]
@giucu91  Here's the link to the dropbox with the zip file requested https://www.dropbox.com/s/z4wxnzxyp0qgue5/membermouse.zip?dl=0
