### ISSUE TITLE
 jQuery Validation v1.19.2 vulnerable

### ISSUE THREAD

**Issue by mplusb** [WPChill/strong-testimonials#300]
update jQuery Validation. 1.19.2 has some known vulnerabilities.

/public/js/lib/validate/jquery-validate.js

```
/*!
 * jQuery Validation Plugin v1.19.2
 *
 * https://jqueryvalidation.org/
 *
 * Copyright (c) 2020 Jörn Zaefferer
 * Released under the MIT license
 */
```

https://wordpress.org/support/topic/jquery-validation-v1-19-2-vulnerable/

**Comment by giucu91** [comment]
duplicate of #292
