### ISSUE TITLE
Importing Testimonials via csv or Wordpress Import/Export not working

### ISSUE THREAD

**Issue by yoursiteneedsme** [WPChill/strong-testimonials#301]
**Describe the bug**
When exporting testimonials from Wordpress TOOLS > Export to a ".xml" file that were entered using the EASY TESTIMONIALS PLUGIN and then trying to import again via Wordpress TOOLS > Import I get this error: Invalid post type testimonial

**To Reproduce**
1. With Easy testimonials installed - Go to Tools > Export and export the file
2. deactivate Easy Testimonials and install Strong Testimonials Pro
3. Go to Tools Import and import the xml file from step 1

**Expected behavior**
The testimonials are able to be imported properly using the xml file

**Screenshots**
![1Xnip-02-28-2022-20](https://user-images.githubusercontent.com/31107658/156057553-96260afa-c190-4e13-b198-b2a070cc9951.jpg)

#### Used versions
* WordPress version: 5.9.1
* Strong Testimonials version: Version 2.51.6. Strong Testimonials PRO version: Version 1.0.5
* Country Selector version: 
* Assignment version: 
* SEO-friendly Markup version: (Review Markup) Version 1.9.6
* Custom Properties version: 
* Advanced Views version: 
* Spam Control version: 
* Pro Templates version: Version 1.2.4
* External Platform Importer version: Version 1.2.2
* Custom Form Fields version: 
* Multiple Forms version:
* Captcha version: Version 1.1.4

**Comment by TeoAlex** [comment]
Importing testimonials from Easy Testimonials plugin is done using https://github.com/WPChill/strong-testimonials-migrate-away-from-easy-testimonials
Using WP importer doesn't work as Easy Testimonials uses 'testimonial' CPT and Strong Testimonials 'wpm-testimonial' CPT. The import can be done using WP importer by editing the export file and replaceing the CPT but this may result in incomplete imports.
