### ISSUE TITLE
Activating Strong Testimonials on a Wordpress 5.9.1 site running Gantry Framework and PHP8.0 causes fatal Gantry error

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/strong-testimonials#302]
**Describe the bug**
I use Strong Testimonials on a number of client sites and I have recently been updating them all to PHP8.0. It has worked on all of the sites except https://ballardsearthmoving.com.au/ and the difference is that Ballards is running Gantry 5 framework.
When I upgrade PHP from 7.4 to 8.0 via cpanel and then visit the backend of the website there is a fatal error and the page doesn't load.
If I then swap back to PHP7.4, deactivate all of the plugins and upgrade to PHP8.0 the backend loads fine. One by one I can reactivate each plugin, but when I activate Strong Testimonials or WP Media Folder then a fatal Gantry error is received (see attached for the error message received when I try to activate Strong Testimonials).
Nothing is logged in error.log on the server.
I have swapped back to PHP7.4, and reactivated the plugin.
Can you investigate and let me know if there is a compatibility issue between WP Media Folder and Gantry5.5.x on PHP8.0?

https://secure.helpscout.net/conversation/1812486581/45246?folderId=4656052

**Comment by TeoAlex** [comment]
Could not reproduce the issue on wp 5.9.1, Gantry framework 5.5.13, php 8.0, Strong Testimonials 2.51.9
