### ISSUE TITLE
 incorrect usage of apply_filter('wp_lazy_loading_enabled')

### ISSUE THREAD

**Issue by mplusb** [WPChill/strong-testimonials#306]
**Describe the bug**

**Feedback from WP Rocket's team:**

We have received some error reports about incorrect usage of apply_filter('wp_lazy_loading_enabled'). I think you might be using the apply_filters( 'wp_lazy_loading_enabled', true ) in an incorrect way in line 127 of: /strong-testimonials/includes/functions-image.php if( !function_exists( 'wp_lazy_loading_enabled' ) \|\| !apply_filters( 'wp_lazy_loading_enabled', true ) ) wp_lazy_loading_enabled is a core hook, and it looks like you are  redeclaring it with only one argument. 
By doing this, any usage of the  wp_lazy_loading_enabled wordpress hook passing more than one argument  will cause an error. On our end, we have this issue reported here: https://github.com/wp-media/wp-rocket/issues/4518, so we can safeguard this. But the issue may happen with other plugins as well.
-- | --

**To Reproduce**

**Expected behavior**

**Screenshots**

* Which addons do you have installed: 
- [ ] Country Selector
- [ ] Assignment
- [ ] SEO-friendly Markup
- [ ] Custom Properties
- [ ] Advanced Views
- [ ] Spam Control
- [ ] Pro Templates
- [ ] External Platform Importer
- [ ] Custom Form Fields
- [ ] Multiple Forms

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 5.9.2
* Strong Testimonials version: 2.51.8
* Country Selector version: 
* Assignment version: 
* SEO-friendly Markup version: 
* Custom Properties version: 
* Advanced Views version: 
* Spam Control version: 
* Pro Templates version: 
* External Platform Importer version: 
* Custom Form Fields version: 
* Multiple Forms version:

**Comment by TeoAlex** [comment]
Was fixed here -> https://github.com/WPChill/strong-testimonials/commit/103fc2fe3b9d1915fde68dcd33cc5a2b672340d1
