### ISSUE TITLE
On empty lists we could use a creation form the same way WP Forms uses

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/strong-testimonials#309]
If there are not posts created we could use a creation form the way WP Forms uses, which could extend the possibilities to let the users discover our functionalities, features and addons.

![Screenshot 2022-04-05 163020](https://user-images.githubusercontent.com/44024114/161765419-10e97e34-cc7b-4321-bba1-287614fd891a.png)

**Comment by TeoAlex** [comment]
Still needs the texts and maby take a look at the colors.

**Comment by cristianraiber** [comment]
@TeoAlex - please post a screenshot here of how it currently looks.

**Comment by TeoAlex** [comment]
@cristianraiber 
![image](https://user-images.githubusercontent.com/19348508/210506624-eedddb05-81d5-4971-aa00-2bb511a4c9a4.png)

**Comment by razvanaldea89** [comment]
This needs a proper banner also

**Comment by incredibeary** [comment]
<img width="924" alt="ST_onboarding_illustration@2x" src="https://user-images.githubusercontent.com/112502248/210526903-d22d7ae5-4cb2-4f98-9cb5-913810a256e7.png">

**Comment by razvanaldea89** [comment]
![image](https://user-images.githubusercontent.com/44024114/210564940-9747dc92-140f-45e3-b2b3-4aaec03790ef.png)

**Comment by razvanaldea89** [comment]
Pending testimonials not taken into consideration
