### ISSUE TITLE
strip post content html

### ISSUE THREAD

**Issue by mplusb** [WPChill/strong-testimonials#311]
**Is your feature request related to a problem? Please describe.**
![04 08 2022-15 33](https://user-images.githubusercontent.com/26008574/162722978-2fdee7e9-95a5-49ae-9b31-80a156ca3855.png)

You will notice on 1 + 2, both of these are bold and italic, the other testimonials are formatted normally.

On the individual testimonial we have formatted them out to include some headings and answers to questions.

When the view pulls in the content and creates the excerpt (see 3), it isn’t stripping the HTML code from the post content, so it’s rendering the opening and tag from the post, this unclosed tag is causing the rest of the content to appear in bold and underline (1) + (2) from screenshot.

I’m going to experiment with different tags like <span> to see if I can get around this, but I thought I’d mention that ideally the plugin should strip HTML from the testimonial content.

**Describe the solution you'd like**

the plugin should strip HTML from the testimonial content. 

**Describe alternatives you've considered**

**Additional context**
https://wordpress.org/support/topic/strip-post-content-html/

**Comment by razvanaldea89** [comment]
If you have a different excerpt than the content, when using the `Read more` functionality different texts will appear ( short text = the true excerpt, long text = the content )

**Comment by razvanaldea89** [comment]
View settings:

![image](https://user-images.githubusercontent.com/44024114/211605886-3e48b9b9-c5b2-404b-a293-cc0215a200f9.png)
