### ISSUE TITLE
slider does not work properly - compatibility issue 

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/strong-testimonials#312]
**Describe the bug**
The live view of the slideshow only shows 1 testimonial. When I edit the page, the preview shows three testimonials - as I have it set up in the Views builder. However, when I go to the live view, it will only show 1 testimonial with no navigation.

the user uses the Divi theme + builder + Jetpack 

https://secure.helpscout.net/conversation/1878054359/46711?folderId=2934192

* Which device is affected (or devices): 
- [x] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other

**Comment by TeoAlex** [comment]
Could not reprodcue the issue.
