### ISSUE TITLE
Gutenberg block select does not look ok

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/strong-testimonials#313]
**Describe the bug**
The select a view is shown very big

**Screenshots**
![image](https://user-images.githubusercontent.com/44024114/169956966-8e3f1083-815e-4c1c-94b9-72effba295b2.png)

**Comment by TeoAlex** [comment]
Coud not preproduce the issue.
Tested with: WordPress 6.1 & Twenty Twenty 2.1, Twenty Twenty-One 1.7, Twenty Twenty-Two 1.3, 
Twenty Twenty-Three 1.0

**Comment by razvanaldea89** [comment]
Seems I can't recreate it either. It may have been some sort of bug that appeared when working in development for other plugins.
