### ISSUE TITLE
 Can’t translate Name/Comany Name with WPML

### ISSUE THREAD

**Issue by mplusb** [WPChill/strong-testimonials#325]
**Describe the bug**
I have a question regarding the Name and Company field. These fields don’t show up among the options when I use Advanced Translation Manager, and as you see from the link to one of the testimonials, the Name field on this website consists of name AND title of the person, and the title is sometimes different in English and French (Director vs Directeur).

I tried to duplicate the testimonial and edit the French translation manually/independently, but it doesn’t save the change, and keeps the English version. 

**To Reproduce**
1. install wpml > add 2,3 languages
2. add a new testimonial in the default language (must have the fields name/company name in the single testimonial) > add name and company name
3. add a translation for this testimonial > and try to change the name/company. You can change them but when you hit save, it defaults back to the initial text

#### Used versions
* WordPress version: 6.0.1
* Strong Testimonials version: 3.0.0

**Comment by TeoAlex** [comment]
The setting preventing the translation of a default custom field value in Strong Testimonials is added via wpml-config.xml file in in .../wp-content/plugins/strong-testimonials/wpml-config.xml as by default the translation of the default custom fields value is not allowed.

If someone wants to be able to translate these, the WPML Strong Testimonials custom fields settings can be overwritten here: 
![image](https://user-images.githubusercontent.com/19348508/200293785-2316d78f-7648-4a7c-8eac-8c17d5684713.png)

1. click the "lock" icon.
2. check the 'Copy once" checkbox.
3. click save.
