### ISSUE TITLE
Error with Wp-Migrate and WPBakery Page Builder

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/strong-testimonials#328]
**Describe the bug**
When moving from Strong Testimonials version 2.51.9 >> 3.0.1 on my website, exports with the WP Migrate plugin do not work and the news Grids made with WPBakery Page Builder disappear (as if I added a display: none to my html) , the new version of the plugin has some bad closed code maybe? Don’t know.

At the moment I have gone back to the Strong Testimonials version 2.51.9

All the best.

Migrate DB PLUGIN: https://es.wordpress.org/plugins/wp-migrate-db/

https://wordpress.org/support/topic/error-with-wp-migrate-and-wpbakery-page-builder/

**Comment by TeoAlex** [comment]
https://github.com/WPChill/strong-testimonials/commit/8a6d9900ab235fc4ac461fae029c5c4900ddccbf fixed here
