### ISSUE TITLE
Conflict with WordPress Export Content

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/strong-testimonials#329]
**Describe the bug**
Trying to track down an issue where the standard wordpress export content option in “Tools” wasn’t working. Disabled all plugins & found “Strong Testimonials” was causing it to fail for some reason. All ok when only this plugin deactivated.
https://wordpress.org/support/topic/conflict-with-wordpress-export-content/

**Comment by TeoAlex** [comment]
https://github.com/WPChill/strong-testimonials/commit/8a6d9900ab235fc4ac461fae029c5c4900ddccbf fixed here.
