### ISSUE TITLE
 Import Testimonials

### ISSUE THREAD

**Issue by mplusb** [WPChill/strong-testimonials#332]
**Describe the bug**
Searching this forum, I learned how to [export ST testimonials](https://wordpress.org/support/topic/export-testimonials-2/) from Tools > Export > Testimonials. After some tweaks I need to import them back from stage to live now.

https://wordpress.org/support/topic/import-testimonials-3/

**Comment by TeoAlex** [comment]
This is the way the WP Import/Export works. It's mainly used to import posts and not update them when editing the XML.
