### ISSUE TITLE
SVG Star Rating has Ugly Border

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/strong-testimonials#337]
**Describe the bug**
One of the recent updates has changed the rating stars to an SVG, which would look good but there is a small black border applied to them, leading to an ugly appearance.

Line 116 of the plugin CSS shows:

.strong-rating-wrapper .star svg path {
    fill: #FFB900;
    stroke: #000;
    stroke-width: 6;
}
This stroke should be removed by default in my opinion.
Please see the site I have linked to – the reviews are at the bottom.
I am viewing it in Chrome.

https://wordpress.org/support/topic/svg-star-rating-has-ugly-border/

**Comment by TeoAlex** [comment]
https://github.com/WPChill/strong-testimonials/commit/d084406dfdf36a6522c8e23b61ad476f79f39438
