### ISSUE TITLE
 HTML formatting doesn't work

### ISSUE THREAD

**Issue by mplusb** [WPChill/strong-testimonials#339]
**Describe the bug**
https://wordpress.org/support/topic/html-formatting-doesnt-work/

**To Reproduce**
can be reproduced with these settings
<img width="1388" alt="Screenshot 2022-09-29 at 14 45 29" src="https://user-images.githubusercontent.com/26008574/193023091-ee3a4795-b44c-47f8-adf2-b456918fbe71.png">
seems to be coming from them

issue coming from functions that does not allow <p> tags

fix from here: https://github.com/WPChill/strong-testimonials/blob/3.0.3/includes/functions-content.php#L171

* Which addons do you have installed: 
- [ ] Country Selector
- [ ] Assignment
- [ ] SEO-friendly Markup
- [ ] Custom Properties
- [ ] Advanced Views
- [ ] Spam Control
- [ ] Pro Templates
- [ ] External Platform Importer
- [ ] Custom Form Fields
- [ ] Multiple Forms

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 6.0.2
* Strong Testimonials version: 3.0.2
* Country Selector version: 
* Assignment version: 
* SEO-friendly Markup version: 
* Custom Properties version: 
* Advanced Views version: 
* Spam Control version: 
* Pro Templates version: 
* External Platform Importer version: 
* Custom Form Fields version: 
* Multiple Forms version:

**Comment by TeoAlex** [comment]
HTML tags are not kept in excerpts; they are being remove by our excerpt function same as wordpress excerpt function does. We can't trim content containing HTML tags as this will more likely result in a broken page.
