### ISSUE TITLE
Update logo

### ISSUE THREAD

**Issue by cristianraiber** [WPChill/strong-testimonials#340]
![st_new_icon_purple](https://user-images.githubusercontent.com/7841556/193558968-84d23485-acad-45a9-9bec-148ebd1a006b.svg)

**Comment by razvanaldea89** [comment]
@cristianraiber did you mean to replace this logo also?


![image](https://user-images.githubusercontent.com/44024114/211352331-16189766-cb4a-46f9-a444-2b8240439c5e.png)

**Comment by cristianraiber** [comment]
Yes
