### ISSUE TITLE
testimonials list disappears if you embed a youtube video in a testimonial

### ISSUE THREAD

**Issue by mplusb** [WPChill/strong-testimonials#341]
**Describe the bug**
testimonials list disappears if you embed a youtube video in a testimonial
screenshot: <img width="1278" alt="Screenshot 2022-10-03 at 15 26 36" src="https://user-images.githubusercontent.com/26008574/193576362-eeca969e-c71c-4063-94f5-aa2e56b61be4.png">
issue started to happen since 3.0.0

2.51.9 - works fine

**To Reproduce**
1. embed a youtube video
2. See error

* Which addons do you have installed: 
- [ ] Country Selector
- [ ] Assignment
- [ ] SEO-friendly Markup
- [ ] Custom Properties
- [ ] Advanced Views
- [ ] Spam Control
- [ ] Pro Templates
- [ ] External Platform Importer
- [ ] Custom Form Fields
- [ ] Multiple Forms

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 6.0.2
* Strong Testimonials version: 3.0.2
* Country Selector version: 
* Assignment version: 
* SEO-friendly Markup version: 
* Custom Properties version: 
* Advanced Views version: 
* Spam Control version: 
* Pro Templates version: 
* External Platform Importer version: 
* Custom Form Fields version: 
* Multiple Forms version:

**Comment by razvanaldea89** [comment]
Can't replicate either, a list with active plugins, theme and how the video was embedded would be useful.

**Comment by mplusb** [comment]
no longer happens with the latest version of the plugin 3.1.9 @razvanaldea89
