### ISSUE TITLE
 PHP Notice coming from Strong Testimonials

### ISSUE THREAD

**Issue by mplusb** [WPChill/strong-testimonials#352]
**Describe the bug**
FYI – Strong Testimonials produces PHP notice:
Notice: Undefined index: continuous_sliding in …/wp-content/plugins/strong-testimonials/includes/class-strong-view-slideshow.php on line 395

This is in latest version of plugin and WordPress

https://wordpress.org/support/topic/php-notice-coming-from-strong-testimonials/

**Comment by stellarwebworks** [comment]
This should be a simple fix, just use isset() or array_key_exists() to check that the index 'continuous_sliding' is defined in $this->atts['slideshow_settings']['continuous_sliding'] (line 395 of class-strong-view-slideshow.php)
