### ISSUE TITLE
Excerpt not hidden when expanded due to JS error 

### ISSUE THREAD

**Issue by Bogardo** [WPChill/strong-testimonials#357]
**Describe the bug**
On a view with Mode `Display` when either the automatic or manual excerpt is enabled, the 'Read more' button shows the full content but keeps the existing excerpt, resulting in duplicate text.
This seems to be caused by a Javascript error:

```
Uncaught TypeError: Cannot set properties of undefined (setting 'display') 
    at HTMLDocument.<anonymous> (readmore.min.jsver=3.0.2:1:1286)
```

**To Reproduce**
1. Create a testimonial with some (long) content
2. Create a _view_ with the following settings:
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/388557/208059226-9b1d7bf0-5175-4544-9e56-ae4305e961c0.png">
With style: Default, image on left, light theme, with a quote symbol in the heading
Layout: normal
Background: inherit from theme
Font color: inherit from theme

3. Place view on Page with shortcode
4. Open page with testimonials
5. Click on 'Read more' button
6. See both excerpt **and** the content of the testimonial

**Expected behavior**
When clicking on the 'Read more' button the excerpt should be hidden and replaced with the full content. Due to the JS error the excerpt is not hidden.

**Demo gif**
![testimonial](https://user-images.githubusercontent.com/388557/208060453-844082d5-0e6b-442d-a986-b197455a765d.gif)

* Which addons do you have installed: (No other plugins (or themes) are installed.)
- [ ] Country Selector
- [ ] Assignment
- [ ] SEO-friendly Markup
- [ ] Custom Properties
- [ ] Advanced Views
- [ ] Spam Control
- [ ] Pro Templates
- [ ] External Platform Importer
- [ ] Custom Form Fields
- [ ] Multiple Forms

* Which browser is affected (or browsers): 
- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [x] Desktop
- [x] Tablet
- [x] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 6.1.1
* Strong Testimonials version: 3.0.2

**Comment by TeoAlex** [comment]
The issue was fixed here https://github.com/WPChill/strong-testimonials/commit/187eaeda5f99b1e86855ebe631d5cc6182ac5722 and released with 3.1.0 update.
