### ISSUE TITLE
Large Black Star on Loading

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/strong-testimonials#359]
**Describe the bug**
on a different website, a large black star appears, just for a split second, on loading or refreshing the page.
See screenshot at https://ibb.co/P9NLGJJ
I am on a MacBook Pro 2020 v12.6 using Chrome v108.0.5359.98 and Safari v 16.2

The page I need help with: https://bestwebsites.ca/reviews-of-us/

https://wordpress.org/support/topic/large-black-star-on-loading/

**To Reproduce**
1. Go to Testimonials > Add stars to your testimonials > go to Views > Display > add the star rating field
2. Add your View on a page > Publish 
3. See error

#### Used versions
* WordPress version: 6.1.1
* Strong Testimonials version: 3.0.2

**Comment by razvanaldea89** [comment]
@TeoAlex any info on why this was happening?

**Comment by TeoAlex** [comment]
This is happening because the stars SVGs and html is loaded before the css; the css is loaded in footer and for slower servers/internet a big star is displayed before the css is applied.
https://user-images.githubusercontent.com/19348508/210748688-af5cb3c8-89a5-4776-804d-4576432506d5.mp4

**Comment by cristianraiber** [comment]
Wouldn't it make more sense to deliver the star SVGs re-scaled down to a smaller size? Since they're SVGs, they can scale up w/ any visual loss in quality. 

cc @razvanaldea89 @TeoAlex

**Comment by razvanaldea89** [comment]
@TeoAlex can you make some tests with what @cristianraiber said and see if downsizing the SVG has any impact?
