### ISSUE TITLE
 Elementor Pro is causing errors in regard to Deprecated functions and hooks.

### ISSUE THREAD

**Issue by mplusb** [WPChill/strong-testimonials#366]
Deprecated: Hook elementor/widgets/widgets_registered is deprecated since version 3.5.0! Use elementor/widgets/register

Deprecated: Function Elementor\Widgets_Manager::register_widget_type is deprecated since version 3.5.0! Use register

Deprecated: Hook elementor/widgets/unregister_widget_type is deprecated since version 3.5.0! Use unregister

https://github.com/WPChill/strong-testimonials/blob/3.1.0/includes/elementor/class-strong-elementor-widget-activation.php#L41

https://github.com/WPChill/strong-testimonials/blob/3.1.0/includes/elementor/class-strong-elementor-widget-activation.php#L35

https://github.com/WPChill/strong-testimonials/blob/3.1.0/includes/elementor/class-strong-elementor-check.php#L116

I cant reproduce, but: https://wordpress.org/support/topic/elementor-pro-is-causing-errors-in-regard-to-deprecated-functions-and-hooks/

#### Used versions
* WordPress version: 6.1.1
* Strong Testimonials version: 3.0.3
elementor pro 3.10.0

**Comment by damienvancouver** [comment]
This bug started showing up yesterday on one of my customer's sites. The site has latest elementor + elementor-pro on it.
```
| elementor                                | active   | none   | 3.10.0        |
| elementor-pro                            | active   | none   | 3.10.1        |
```
After latest updates there were three deprecation warnings with WP_DEBUG active in wp-config.php, as reported in https://wordpress.org/support/topic/elementor-pro-is-causing-errors-in-regard-to-deprecated-functions-and-hooks/.

a "grep -irl widgets_registered' in our codebase showed that strong-testimonials was the only plugin calling these deprecated functions (ie. the only place it appears other than in elementor itself):

```
# grep -irl 'widgets_registered'
wp-content/plugins/strong-testimonials/includes/elementor/class-strong-elementor-widget-activation.php
wp-content/plugins/strong-testimonials/includes/elementor/class-strong-elementor-check.php
wp-content/plugins/elementor/readme.txt
wp-content/plugins/elementor/includes/managers/widgets.php

```
Sure enough, on the Elementor 3.5 readme they explain the deprecation:
https://developers.elementor.com/v3-5-planned-deprecations/

Now the weird part.. in troubleshooting this I deactivated and reactivated strong-testimonials.  Now I have done that, the deprecation errors are gone, even with WP_DEBUG active again.  That may be why you can't reproduce it??  But in any case, you should be able to update to the new hook names by virtue of the elementor docs there and just renaming to the correct ones.  for now it's a soft deprecation but eventually it wlil break like that.. and it causes havoc with WP_DEBUG on when those messages show.

strong-testimonials is not alone in not having seen the memo, tons of plugins are affected, even Google reCAPTCHA!  See: https://wordpress.org/support/topic/deprecated-version-3-5-error/ 

Good luck! 

D.
