### ISSUE TITLE
search feature does not work 

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/strong-testimonials#377]
**Describe the bug**
In the WP dashboard, when I search testimonials by name of submitter, nothing comes up.
https://secure.helpscout.net/conversation/2166516111/54855?folderId=4656052

**To Reproduce**
1. Go to dashboard > Testimonials > add a testimonial > search by the name of the client 
2. See error

#### Used versions
* WordPress version: 6.1.1
* Strong Testimonials version: 3.1.1

**Comment by razvanaldea89** [comment]
Don't think this was an option, but we can look into it.
