### ISSUE TITLE
Read more tag not working

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/strong-testimonials#378]
**Describe the bug**
In the “Views” setup – If I set the “Fields” section to “automatic excerpt”, my text formatting doesn’t work (there are no line breaks and bold text doesn’t show – see https://screenshots.russellharris.de/screenshot_1.jpg). It warns me of this (This will strip tags like <em> and <strong>).
So, I changed the setting to “entire content”.
Now, when I view the page the “read more” tag, which I inserted into the first testimonial (after the text “Stück absoluter Musik, das drei programmatischen Sinfonien folgte….” – see https://screenshots.russellharris.de/screenshot_2.jpg) is not showing. So I cannot expand the text.
https://wordpress.org/support/topic/read-more-tag-not-working-12/

**Comment by TeoAlex** [comment]
"Automatic excerpt" removes the html tags in the excerpt and this is the reason line breaks and bold text doesn't work. Clicking on "Read More", the full text displays including the html  tags ( bold, line breaks, etc. )

"Entire content" displays the full testimonial content including the html tags. The "Read More" button won't be available as the full content is allready displayed.

We found out that <p> (paragraph) tags won't show up in the full content ( read more content) and a small fix will be implemented.
