### ISSUE TITLE
clicking on read more doesn't seem to do anything

### ISSUE THREAD

**Issue by madhums** [WPChill/strong-testimonials#389]
**Describe the bug**
Clicking on read more doesn't seem to do anything.

**To Reproduce**
1. Click on "read more" link
2. Nothing happens (nor there's any javascript error)

**Expected behavior**
- The testimonial should expand.

Which addons do you have installed: 
- [x] Advanced WordPress Backgrounds
- [x] Better Font Awesome
- [x] Custom Fonts
- [x] EWWW Image Optimizer
- [x] Jetpack
- [x] Limit Login Attempts Reloaded
- [x] Matomo Analytics - Ethical Stats. Powerful Insights.
- [x] Smash Balloon Custom Facebook Feed
- [x] UpdraftPlus - Backup/Restore
- [x] Widgets for Google Reviews
- [x] Yoast SEO
- [x] Theme: [wp-astra](https://wpastra.com/)

Which browser is affected (or browsers): 
- [x] Brave
- [x] Firefox
- [x] Safari

Which device is affected (or devices): 
- [x] Desktop
- [x] Tablet
- [x] Mobile

#### Used versions
* WordPress version: 6.1.1
* Strong Testimonials version: 3.1.3
* latest version of all other plugins
* wpastra theme 4.1.1

**Comment by razvanaldea89** [comment]
Hey @madhums ,

Could you please give a link to the website so I can have a look?

Warmly,
Razvan

**Comment by TeoAlex** [comment]
Re-tested with both automatic and manual excerpt and the "read more" button is working and the issue could not be reproduced.
