### ISSUE TITLE
the columns in masonry layout are too small 

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/strong-testimonials#404]
**Describe the bug**
If you choose the masonry layout in your view and set it to 3 or 4 columns the columns won't be displayed properly 

**Screenshots**
![image](https://github.com/WPChill/strong-testimonials/assets/84579642/0e4342f6-a719-4419-8b56-9f45fbd64f54)

#### Used versions
* WordPress version: 6.2.2
* Strong Testimonials version: 3.1.7

**Comment by TeoAlex** [comment]
There is no issue with the columns layout. If you choose 3-4 columns and the width of the container is not enough so all columns fit properly the only thing that can be done is 1. increase the width of the container or 2. decrease the number of columns.

**Comment by razvanaldea89** [comment]
Agree, they are small because of the width of the container. Going to close this.
