### ISSUE TITLE
PHP Warning in error.log

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/strong-testimonials#434]
**Describe the bug**
I’ve noticed the following PHP warning in the error.log file:

19-Mar-2024 00:23:46 UTC] PHP Warning: Trying to access array offset on value of type bool in /home/zs70nqh/public_html/wp-content/plugins/strong-testimonials/includes/functions-image.php on line 183

This is running WP 6.4.3, PHP 8.2.16, Apache and MySQL 8.0.36 with Astra Pro theme. 

https://wordpress.org/support/topic/php-warning-in-error-log-13/

**Comment by TeoAlex** [comment]
To test, set this setting in ST view & have a testimonial without email address or with an invalid email address.
![image](https://github.com/user-attachments/assets/b67fb242-88d0-4990-98b0-6d2083fa2e78)
