### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by cristeacosmin** [WPChill/strong-testimonials#450]
![image](https://github.com/user-attachments/assets/da987b52-77b6-4f55-8c4b-a463e86bc63f)

**Comment by cristeacosmin** [comment]
![image](https://github.com/user-attachments/assets/d7faa8f7-329b-4021-9ca1-8af7909effbb)

**Comment by TeoAlex** [comment]
https://github.com/WPChill/strong-testimonials/commit/4ed7ca07f8723a8bcb8e9bc9f11c0816f376ef78
