### ISSUE TITLE
Welcome page doesn't look good

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/strong-testimonials#455]
**Describe the bug**
The columns are disproportioned, most probably from the submodule.

**Screenshots**
![image](https://github.com/user-attachments/assets/9476de4f-ff23-4cd5-aadc-b0194da338e7)

* Which addons do you have installed: 
- [ ] Country Selector
- [ ] #460
- [ ] #459
- [ ] Custom Properties
- [ ] Advanced Views
- [ ] Spam Control
- [ ] Pro Templates
- [ ] External Platform Importer
- [ ] Custom Form Fields
- [ ] Multiple Forms

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Strong Testimonials version: 
* Country Selector version: 
* Assignment version: 
* SEO-friendly Markup version: 
* Custom Properties version: 
* Advanced Views version: 
* Spam Control version: 
* Pro Templates version: 
* External Platform Importer version: 
* Custom Form Fields version: 
* Multiple Forms version:

**Comment by cristianraiber** [comment]
Remove welcome page
