### ISSUE TITLE
PHP 8.1+ FILTER_SANITIZE_STRING deprecation

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/strong-testimonials#457]
Deprecated: Constant FILTER_SANITIZE_STRING

**Comment by cristinnaiulia** [comment]
The warnings are gone, but I have this space in admin -> view area when I have the debug set to true:
![Screenshot 2024-07-19 090518](https://github.com/user-attachments/assets/2984aee8-cc1d-40f6-8623-030a9188f659)
