### ISSUE TITLE
Apply custom font color to extra fields too

### ISSUE THREAD

**Issue by TeoAlex** [WPChill/strong-testimonials#463]
All texts should be custom color (here -> green ) 
![image](https://github.com/user-attachments/assets/7e95a31d-34c6-4c79-8e42-376fd120f282)

**Comment by andrei-l-cristea** [comment]
There seems to be an issue when you have a testimonial with readmore, in this case the custom color is not taken into account:
<img width="1348" alt="Screenshot 2024-08-07 at 17 21 02" src="https://github.com/user-attachments/assets/17245eda-21fa-401a-8472-300abbff5890">

**Comment by cristinnaiulia** [comment]
+1
![Screenshot 2024-08-08 101015](https://github.com/user-attachments/assets/cecd8d64-1ce4-4009-b892-e8e22ddd1b52)
