### ISSUE TITLE
 Gutenberg Block

### ISSUE THREAD

**Issue by mplusb** [WPChill/strong-testimonials#87]
add a Gutenberg block to this plugin to make it possible to use visually in the Block Editor without resorting to shortcodes

**Comment by Florin415** [comment]
Could not find the block in the Block Editor

**Comment by andyluak** [comment]
@Florin415 The block is in branch gutemberg-block.

**Comment by Florin415** [comment]
@andyluak  I pulled the code from the branch on a new local , went to the change a page and add on it a new block but still could not find the block. I've made a video that shows all the blocks that can be added , if I missed a step regarding on how to add the block please tell me : https://www.screencast.com/t/xFZOQuJQQy3Y
